### PR TITLE
The pull request will pass all the arguments passed to Feedbag#find to to OpenURI 

### PR DESCRIPTION
**Pull request by dkam**
The Options will get passed to URI#open, so it should solve #21 and #23 .

This pull request includes all the changes in #26.

You can do: `Feedbag.find("https://booko.info", "User-Agent" => "Direct", open_timeout: 1000)`

### CODE REVIEW

**Comment by dkam** [comment]
I also have a branch which removes `open_uri_redirections` - I can merge that into this change too if you like?

**Comment by damog** [comment]
Thanks @dkam. Any way that tests cases could be added to guard backward compatibility?

**Comment by skatkov** [comment]
A lot of great improvements here. @dkam do you need a hand with tests?

**Comment by dkam** [comment]
Oh hi!  Let me wrap my head around it again.

**Comment by dkam** [comment]
I've added tests for 
* following redirection 
* A default User-Agent is set
* User-Agent can be overridden. 

How does that look?

**Comment by damog** [comment]
Hi @dkam – thanks a lot for working on this.

What is the required Ruby version for these changes? I'm testing on `2.6.8` and the tests won't pass:

```
➜  ~/git/feedbag git:(dkam-options) ruby -Ilib -Itest test/feedbag_test.rb
Mocha deprecation warning at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
Loaded suite test/feedbag_test
Started
E
============================================================================================================================================================================================================================================================================================================================================================================
test/feedbag_test.rb:57:in `block in create_test_from_should_hash'
test/feedbag_test.rb:57:in `instance_exec'
test/feedbag_test.rb:52:in `block (2 levels) in <class:FeedbagTest>'
/Users/damog/git/feedbag/lib/feedbag.rb:47:in `find'
Error: test: Feedbag find should discover JSON Feeds should find json feed. (FeedbagTest): TypeError: hash key "User-Agent" is not a Symbol
============================================================================================================================================================================================================================================================================================================================================================================
E
============================================================================================================================================================================================================================================================================================================================================================================
test/feedbag_test.rb:37:in `block in create_test_from_should_hash'
test/feedbag_test.rb:37:in `instance_exec'
test/feedbag_test.rb:30:in `block (2 levels) in <class:FeedbagTest>'
test/feedbag_test.rb:30:in `each'
test/feedbag_test.rb:31:in `block (3 levels) in <class:FeedbagTest>'
/Users/damog/git/feedbag/lib/feedbag.rb:47:in `find'
Error: test: Feedbag find should discover feeds containing atom:link should find atom feed. (FeedbagTest): TypeError: hash key "User-Agent" is not a Symbol
============================================================================================================================================================================================================================================================================================================================================================================
E
============================================================================================================================================================================================================================================================================================================================================================================
test/feedbag_test.rb:69:in `block in create_test_from_should_hash'
test/feedbag_test.rb:69:in `instance_exec'
test/feedbag_test.rb:67:in `block (2 levels) in <class:FeedbagTest>'
/Users/damog/git/feedbag/lib/feedbag.rb:47:in `find'
Error: test: Feedbag should follow redirects should follow redirects. (FeedbagTest): TypeError: hash key "User-Agent" is not a Symbol
============================================================================================================================================================================================================================================================================================================================================================================
E
============================================================================================================================================================================================================================================================================================================================================================================
test/feedbag_test.rb:81:in `block in create_test_from_should_hash'
test/feedbag_test.rb:81:in `instance_exec'
test/feedbag_test.rb:80:in `block (2 levels) in <class:FeedbagTest>'
/Users/damog/git/feedbag/lib/feedbag.rb:47:in `find'
Error: test: Feedbag should send the correct User Agent should send correct user agent. (FeedbagTest): TypeError: hash key "User-Agent" is not a Symbol
============================================================================================================================================================================================================================================================================================================================================================================
...
Finished in 0.00182 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
7 tests, 6 assertions, 0 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
42.8571% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3846.15 tests/s, 3296.70 assertions/s
➜  ~/git/feedbag git:(dkam-options) ruby --version
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
➜  ~/git/feedbag git:(dkam-options)
```

Thoughts?

**Comment by damog** [comment]
Confirmed tests pass with `3.1.1`.

```
➜  ~/git/feedbag git:(dkam-options) ruby -Ilib -Itest test/feedbag_test.rb
Mocha deprecation warning at <internal:/Users/damog/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
Loaded suite test/feedbag_test
Started
.......
Finished in 2.384258 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
7 tests, 16 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2.94 tests/s, 6.71 assertions/s
➜  ~/git/feedbag git:(dkam-options) ruby --version
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
➜  ~/git/feedbag git:(dkam-options)
```

**Comment by dkam** [comment]
Looks like I was using 3.0.2.  I can't install 2.7.0 or 2.7.1 but it passes tests with 2.7.2.  2.6.9 will [EOL Soon](https://www.ruby-lang.org/en/downloads/) - ok if we set a Ruby version requirement of >= 2.7.2?

**Comment by dkam** [comment]
Hi @damog - anything needed for this pull request?

**Comment by damog** [comment]
Thanks for your contributions and patience @dkam. I've now published 0.10.2.  🥇

**Pull request merged**
